name: Publish to GitHub Packages

on:
  release:
    types: [published, created]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@agunggnn'

      - name: Install dependencies
        run: npm ci

      - name: Run checks & test suite
        run: npm run check

      - name: Publish package to GitHub Packages
        run: npm publish || echo "Package version already published to registry, skipping."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
